### ISSUE TITLE
Having problem while following instructions.

### ISSUE THREAD

**Issue by usas0s** [FZFalzar/skel2json_v4.0#1] opened 2022-12-29 17:30 UTC
Hello. 

I'm having a problem with following instructions.
It's not easy to fix it by myself because I'm very new with nodeJS.

1.
![image](https://user-images.githubusercontent.com/2849204/209987528-37602078-e1b8-4002-ac56-3ad1a83b441a.png)

I'm having "Cannot use import statement outside a module" error while following instruction.

2.
![image](https://user-images.githubusercontent.com/2849204/209987685-771d412f-6749-42bf-8835-e06b41f26c15.png)

(Maybe missing semi colon at end of line?)

3.
![image](https://user-images.githubusercontent.com/2849204/209987954-cce08edf-8bb4-4176-8ecd-3ceeca9e7f46.png)

I googled and found solution.
I've made new package.json file next to index.js because "type": "module" line will fix that error.

4.
![image](https://user-images.githubusercontent.com/2849204/209988028-3c1372f3-8eb1-4e71-b311-50db4c474f95.png)

Now error was fixed but something wrong with result file..

Can you tell me how to fix this situation? 
I wanna get json file!

Thanks.

**Comment by FZFalzar** [comment] 2022-12-30 03:39
Hi, I have updated the repo to hopefully fix the error, please check and clone latest commit

**Comment by usas0s** [comment] 2022-12-30 08:19
![image](https://user-images.githubusercontent.com/2849204/210048677-6c22fae4-a680-4e91-904f-a3242a6eca35.png)

Now I can get json file successfully as shown in the screenshot.
Seems problem has been solved.

But having crash when I load model with [SpineViewerWPF](https://github.com/kiletw/SpineViewerWPF/releases/tag/2.4.0.0) and [Spine Android](https://github.com/keith2018/spine-opengl)
I guess the problem is on Spine version compatibility, not skel2json script...

Thx a lot!

**Comment by FZFalzar** [comment] 2022-12-30 17:46
NIKKE's skeletons are using 4.0.47, if the runtime version does not match the model will not load properly

Otherwise I'm glad the problem is solved for you, closing the issue

**Closed as completed by FZFalzar** 2022-12-30 17:46 UTC
